import { ClerkProvider,SignIn } from '@clerk/nextjs'
import './globals.css'
import type { Metadata } from 'next'
import { Unbounded } from 'next/font/google'
import { SignedIn } from '@clerk/nextjs/app-beta'
import { SignedOut } from '@clerk/nextjs/app-beta/client'
import NavBar from '@/components/NavBar'

const inter = Unbounded({ subsets: ['cyrillic-ext'] })

export const metadata: Metadata = {
  title: 'Zuret Rentals',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <SignedIn>
          <NavBar/>
        {children}
        </SignedIn>
        <SignedOut>
          <SignIn/>
        </SignedOut>
        </body>
    </html>
    </ClerkProvider>
  )
}
